name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:

  build-linux::
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup deps
      run: |
        sudo apt-get update -y
        sudo apt-get install -y intltool automake libglib2.0-dev libgimp2.0-dev
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make install
      run: sudo make install
    - uses: actions/upload-artifact@v1
      with:
        name: lib-linux
        path: .

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Msys2 environment
      uses: numworks/setup-msys2@v1
